FROM registry.access.redhat.com/ubi10/go-toolset:10.0 AS builder
WORKDIR /app/backend
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN chgrp -R 0 . && \
    chmod -R g+rwX .
RUN go build -o guestbook-api
RUN chmod g+x guestbook-api

FROM registry.access.redhat.com/ubi10:10.0
WORKDIR /app
COPY --from=builder /app/backend/guestbook-api .
RUN chgrp -R 0 /app && \
    chmod -R g+rwX /app && \
    chmod g+x guestbook-api
EXPOSE 8080
CMD ["./guestbook-api"]
