FROM registry.access.redhat.com/ubi10/go-toolset:10.0 AS builder
WORKDIR /app/backend
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN id
RUN ls -la .
RUN go build -o /tmp/guestbook-api

FROM registry.access.redhat.com/ubi10:10.0
WORKDIR /app
COPY --from=builder /tmp/guestbook-api .
RUN id
RUN ls -la .
USER 1001
EXPOSE 8080
CMD ["./guestbook-api"]
